[my::array] support naive std::copy for my::array
- It's easy. Just make begin(),end() function members.
- They must returns pointers, because std::copy makes dereference.

Error, if they return int:

error: indirection requires  pointer operand ('int' invalid)
  *__result = *__first;

TODO: deep into real iterators